#!/usr/bin/env bash
# This script displays numbers from 1 to 20 but in 4, 9 and 17
i=0
while ((i < 20))
    do
    ((i++))
    echo $i
    case $i in
	4)
	    echo "bad luck from China"
	    ;;
	9)
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "bad luck from Italy"
	    ;;
    esac
done
